#ifndef MHTTP_HTTP_H
#define MHTTP_HTTP_H

enum mhttp_result {
	MHTTP_OK,
	MHTTP_NEED_MORE_INPUT,
	MHTTP_INVALID_REQUEST,
	MHTTP_ERROR
};

enum mhttp_method {
	MHTTP_METHOD_GET,
	MHTTP_METHOD_HEAD,
	MHTTP_METHOD_POST,
	MHTTP_METHOD_PUT,
	MHTTP_METHOD_DELETE,
	MHTTP_METHOD_OPTIONS,
	MHTTP_METHOD_PATCH
};

enum mhttp_status_code {
	MHTTP_STATUS_OK = 200,
	MHTTP_STATUS_BAD_REQUEST = 400,
	MHTTP_STATUS_NOT_FOUND = 404,
	MHTTP_STATUS_INTERNAL_SERVER_ERROR = 500
};

#define MHTTP_MAX_HEADERS 100
#define MHTTP_HEADER_NAME_SIZE 256
#define MHTTP_HEADER_VALUE_SIZE 256

struct mhttp_header {
	struct mhttp_header *next;
	char name[MHTTP_HEADER_NAME_SIZE];
	char value[MHTTP_HEADER_VALUE_SIZE];
};

#endif // MHTTP_HTTP_H
